[default]
DATAVERSE_NL_URL="https://dataverse.nl"
SSH_DATASTATION_URL="https://ssh.datastations.nl"

TWENTE={"ALIAS"="twente", "OAI_SET"="@format {this.TWENTE_OAI_SET}", "BUCKET_NAME"="@format {this.TWENTE_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
DELFT={"ALIAS"="delft", "OAI_SET"="@format {this.DELFT_OAI_SET}", "BUCKET_NAME"="@format {this.DELFT_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
AVANS={"ALIAS"="AvansHogeschool", "OAI_SET"="@format {this.AVANS_OAI_SET}", "BUCKET_NAME"="@format {this.AVANS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
FONTYS={"ALIAS"="fontys", "OAI_SET"="@format {this.FONTYS_OAI_SET}", "BUCKET_NAME"="@format {this.FONTYS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
GRONINGEN={"ALIAS"="groningen", "OAI_SET"="@format {this.GRONINGEN_OAI_SET}", "BUCKET_NAME"="@format {this.GRONINGEN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HANZE={"ALIAS"="hanze", "OAI_SET"="@format {this.HANZE_OAI_SET}", "BUCKET_NAME"="@format {this.HANZE_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HR={"ALIAS"="hr", "OAI_SET"="@format {this.HR_OAI_SET}", "BUCKET_NAME"="@format {this.HR_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
LEIDEN={"ALIAS"="leidenuniversity", "OAI_SET"="@format {this.LEIDEN_OAI_SET}", "BUCKET_NAME"="@format {this.LEIDEN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
MAASTRICHT={"ALIAS"="maastricht", "OAI_SET"="@format {this.MAASTRICHT_OAI_SET}", "BUCKET_NAME"="@format {this.MAASTRICHT_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TILBURG={"ALIAS"="tiu", "OAI_SET"="@format {this.TILBURG_OAI_SET}", "BUCKET_NAME"="@format {this.TILBURG_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TRIMBOS={"ALIAS"="trimbos", "OAI_SET"="@format {this.TRIMBOS_OAI_SET}", "BUCKET_NAME"="@format {this.TRIMBOS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UMCU={"ALIAS"="UMCU", "OAI_SET"="@format {this.UMCU_OAI_SET}", "BUCKET_NAME"="@format {this.UMCU_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UTRECHT={"ALIAS"="UU", "OAI_SET"="@format {this.UTRECHT_OAI_SET}", "BUCKET_NAME"="@format {this.UTRECHT_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
VU={"ALIAS"="vuamsterdam", "OAI_SET"="@format {this.VU_OAI_SET}", "BUCKET_NAME"="@format {this.VU_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
DANS={"ALIAS"="dans", "OAI_SET"="@format {this.DANS_OAI_SET}", "BUCKET_NAME"="@format {this.DANS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.SSH_DATASTATION_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATASTATION_REFINER_ENDPOINT}"}
CBS={"ALIAS"="cbs", "BUCKET_NAME"="@format {this.CBS_BUCKET_NAME}", "TEMPLATE_FILE_PATH"="@format {this.CBS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.CBS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.CBS_REFINER_ENDPOINT}"}
LISS={"ALIAS"="liss", "BUCKET_NAME"="@format {this.LISS_BUCKET_NAME}", "TEMPLATE_FILE_PATH"="@format {this.LISS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.LISS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
HSN={"ALIAS"="HSN_NL", "BUCKET_NAME"="@format {this.HSN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.IISG_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
CID={"ALIAS"="cid", "BUCKET_NAME"="@format {this.CID_BUCKET_NAME}", "TEMPLATE_FILE_PATH"="@format {this.CID_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.CID_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.CID_REFINER_ENDPOINT}"}

TWENTE_OAI_SET = "Twente_Social_Sciences"
DELFT_OAI_SET = "TUDelft_Social_Sciences"
AVANS_OAI_SET = "Avans_Social_Sciences"
FONTYS_OAI_SET = "Fontys_social_sciences"
GRONINGEN_OAI_SET = "Groningen_Social_Sciences"
HANZE_OAI_SET = "Hanze_Social_Sciences"
HR_OAI_SET = "HR_Social_Sciences"
LEIDEN_OAI_SET = "Leiden_Social_Sciences"
MAASTRICHT_OAI_SET = "Maastricht_Social_Sciences"
TILBURG_OAI_SET = "Tilburg_Social_Sciences"
TRIMBOS_OAI_SET = "Trimbos_Social_Sciences"
UMCU_OAI_SET = "UMCU_Social_Sciences"
UTRECHT_OAI_SET = "UU_Social_Sciences"
VU_OAI_SET = "VU_Social_Sciences"
DANS_OAI_SET = "social_sciences"

TWENTE_BUCKET_NAME="dataverse.nl-twente"
DELFT_BUCKET_NAME="dataverse.nl-delft"
AVANS_BUCKET_NAME="dataverse.nl-avans"
FONTYS_BUCKET_NAME="dataverse.nl-fontys"
GRONINGEN_BUCKET_NAME="dataverse.nl-groningen"
HANZE_BUCKET_NAME="dataverse.nl-hanze"
HR_BUCKET_NAME="dataverse.nl-hr"
LEIDEN_BUCKET_NAME="dataverse.nl-leiden"
MAASTRICHT_BUCKET_NAME="dataverse.nl-maastricht"
TILBURG_BUCKET_NAME="dataverse.nl-tilburg"
TRIMBOS_BUCKET_NAME="dataverse.nl-trimbos"
UMCU_BUCKET_NAME="dataverse.nl-umc"
UTRECHT_BUCKET_NAME="dataverse.nl-utrecht"
VU_BUCKET_NAME="dataverse.nl-vu"
CBS_BUCKET_NAME="cbs-metadata-03072023"
DANS_BUCKET_NAME="ssh-social-metadata"
LISS_BUCKET_NAME="liss-metadata"
HSN_BUCKET_NAME="hsn-metadata"
CID_BUCKET_NAME="cid-metadata"

DATAVERSE_NL_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"
CBS_REFINER_ENDPOINT="/metadata-refinement/cbs"
DATASTATION_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"
HSN_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"
CID_REFINER_ENDPOINT="/metadata-refinement/cid"


CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

CID_TEMPLATE_FILE_PATH="/resources/templates/cid_dataverse_template.json"
CID_MAPPING_FILE_PATH="/resources/mappings/cid-mapping.json"

[development]
ODISSEI_URL="http://dataverse:8080"

[staging]
ODISSEI_URL="https://portal.alpha.odissei.nl"

[production]
ODISSEI_URL="https://portal.odissei.nl"
