version: '3.7'

services:
  prefect:
    build:
      context: prefect_docker/.
      dockerfile: Dockerfile
    container_name: 'prefect'
    volumes:
      - "/tmp:/tmp"
      - ./prefect_docker/scripts:/scripts/
      - ./local-metadata:/local-metadata/
      - ./resources:/resources/
    ports:
      # Local development only
      - "4200:4200"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lolgres
      - POSTGRES_DB=prefect
