version: '3.7'

services:
  prefect-museit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'prefect-museit'
    image: thomasve/prefect3:latest
    volumes:
      - "/tmp:/tmp"
      - "./scripts:/scripts"
    ports:
      # Local development only
      - 4200:4200
    env_file: .env
    depends_on:
      - prefectdb
    networks:
      - prefect

  prefect-agent-1:
    container_name: 'prefect-agent-1'
    image: thomasve/prefect3:latest
    depends_on:
      - prefect-museit
    networks:
      - prefect
    entrypoint: ["/usr/local/bin/entrypoint-agent.sh"]

  prefect-agent-2:
    container_name: 'prefect-agent-2'
    image: thomasve/prefect3:latest
    depends_on:
      - prefect-museit
    networks:
      - prefect
    entrypoint: ["/usr/local/bin/entrypoint-agent-2.sh"]

  prefectdb:
    image: postgres:latest
    container_name: prefectdb
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lolgres
      - POSTGRES_DB=prefect
    ports:
      - 5432:5432
    networks:
      - prefect

networks:
  prefect:
    external: true
