[default]
DATAVERSE_NL_URL="https://dataverse.nl"
SSH_DATASTATION_URL="https://ssh.datastations.nl"
DATAVERSE_NL_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"
CBS_REFINER_ENDPOINT="/metadata-refinement/cbs"
DATASTATION_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"
HSN_REFINER_ENDPOINT="/metadata-refinement/dataverse-nl"

RESEARCH_DATA={"ALIAS"="4tu", "BUCKET_NAME"="@format {this.RESEARCH_DATA_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
AVANS={"ALIAS"="AvansHogeschool", "BUCKET_NAME"="@format {this.AVANS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
FONTYS={"ALIAS"="fontys", "BUCKET_NAME"="@format {this.FONTYS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
GRONINGEN={"ALIAS"="groningen", "BUCKET_NAME"="@format {this.GRONINGEN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HANZE={"ALIAS"="hanze", "BUCKET_NAME"="@format {this.HANZE_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HR={"ALIAS"="hr", "BUCKET_NAME"="@format {this.HR_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
LEIDEN={"ALIAS"="leidenuniversity", "BUCKET_NAME"="@format {this.LEIDEN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
MAASTRICHT={"ALIAS"="maastricht", "BUCKET_NAME"="@format {this.MAASTRICHT_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TILBURG={"ALIAS"="tiu", "BUCKET_NAME"="@format {this.TILBURG_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TRIMBOS={"ALIAS"="trimbos", "BUCKET_NAME"="@format {this.TRIMBOS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UMCU={"ALIAS"="UMCU", "BUCKET_NAME"="@format {this.UMCU_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UTRECHT={"ALIAS"="UU", "BUCKET_NAME"="@format {this.UTRECHT_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
VU={"ALIAS"="vuamsterdam", "BUCKET_NAME"="@format {this.VU_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
DANS={"ALIAS"="dans", "BUCKET_NAME"="@format {this.DANS_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.SSH_DATASTATION_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATASTATION_REFINER_ENDPOINT}"}
CBS={"ALIAS"="cbs", "BUCKET_NAME"="@format {this.CBS_BUCKET_NAME}", "TEMPLATE_FILE_PATH"="@format {this.CBS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.CBS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.CBS_REFINER_ENDPOINT}"}
LISS={"ALIAS"="liss", "BUCKET_NAME"="@format {this.LISS_BUCKET_NAME}", "TEMPLATE_FILE_PATH"="@format {this.LISS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.LISS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
HSN={"ALIAS"="HSN_NL", "BUCKET_NAME"="@format {this.HSN_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.IISG_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.HSN_REFINER_ENDPOINT}"}


DATAVERSE_NL_BUCKET_NAME="dataverse.nl-metadata"
RESEARCH_DATA_BUCKET_NAME="dataverse.nl-4tu"
AVANS_BUCKET_NAME="dataverse.nl-avans"
FONTYS_BUCKET_NAME="dataverse.nl-fontys"
GRONINGEN_BUCKET_NAME="dataverse.nl-groningen"
HANZE_BUCKET_NAME="dataverse.nl-hanze"
HR_BUCKET_NAME="dataverse.nl-hr"
LEIDEN_BUCKET_NAME="dataverse.nl-leiden"
MAASTRICHT_BUCKET_NAME="dataverse.nl-maastricht"
TILBURG_BUCKET_NAME="dataverse.nl-tilburg"
TRIMBOS_BUCKET_NAME="dataverse.nl-trimbos"
UMCU_BUCKET_NAME="dataverse.nl-umc"
UTRECHT_BUCKET_NAME="dataverse.nl-utrecht"
VU_BUCKET_NAME="dataverse.nl-vu"
CBS_BUCKET_NAME="cbs-metadata"
DANS_BUCKET_NAME="ssh-social-metadata"
LISS_BUCKET_NAME="liss-metadata"
HSN_BUCKET_NAME="hsn-metadata"

[development]
ODISSEI_URL="http://dataverse:8080"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

[staging]
ODISSEI_URL="https://portal.dev.odissei.nl"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

[production]
ODISSEI_URL="https://portal.staging.odissei.nl"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"
