[default]
DATAVERSE_NL_URL="https://dataverse.nl"

DATAVERSE_NL={"ALIAS"="dataverse_nl", "METADATA_DIRECTORY"="@format {this.DATAVERSE_NL_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
RESEARCH_DATA={"ALIAS"="4tu", "METADATA_DIRECTORY"="@format {this.RESEARCH_DATA_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
AVANS={"ALIAS"="AvansHogeschool", "METADATA_DIRECTORY"="@format {this.AVANS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
FONTYS={"ALIAS"="fontys", "METADATA_DIRECTORY"="@format {this.FONTYS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
GRONINGEN={"ALIAS"="groningen", "METADATA_DIRECTORY"="@format {this.GRONINGEN_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
HANZE={"ALIAS"="hanze", "METADATA_DIRECTORY"="@format {this.HANZE_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
HR={"ALIAS"="hr", "METADATA_DIRECTORY"="@format {this.HR_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
LEIDEN={"ALIAS"="leidenuniversity", "METADATA_DIRECTORY"="@format {this.LEIDEN_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
MAASTRICHT={"ALIAS"="maastricht", "METADATA_DIRECTORY"="@format {this.MAASTRICHT_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
TILBURG={"ALIAS"="tiu", "METADATA_DIRECTORY"="@format {this.TILBURG_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
TRIMBOS={"ALIAS"="trimbos", "METADATA_DIRECTORY"="@format {this.TRIMBOS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
UMCU={"ALIAS"="UMCU", "METADATA_DIRECTORY"="@format {this.UMCU_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
UTRECHT={"ALIAS"="UU", "METADATA_DIRECTORY"="@format {this.UTRECHT_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
VU={"ALIAS"="vuamsterdam", "METADATA_DIRECTORY"="@format {this.VU_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "SOURCE_DATAVERSE_API_KEY"="@format {this.DATAVERSE_NL_API_KEY}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}

CBS={"ALIAS"="cbs", "METADATA_DIRECTORY"="@format {this.CBS_METADATA_DIRECTORY}", "TEMPLATE_FILE_PATH"="@format {this.CBS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.CBS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
EASY={"ALIAS"="easy", "METADATA_DIRECTORY"="@format {this.EASY_METADATA_DIRECTORY}", "TEMPLATE_FILE_PATH"="@format {this.EASY_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.EASY_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}
LISS={"ALIAS"="liss", "METADATA_DIRECTORY"="@format {this.LISS_METADATA_DIRECTORY}", "TEMPLATE_FILE_PATH"="@format {this.LISS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.LISS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}


[development]
ODISSEI_URL="http://dataverse:8080"

DATAVERSE_NL_METADATA_DIRECTORY="dataverse_nl-metadata"
RESEARCH_DATA_METADATA_DIRECTORY="dataverse_nl/4tu"
AVANS_METADATA_DIRECTORY="dataverse_nl/avans"
FONTYS_METADATA_DIRECTORY="dataverse_nl/fontys"
GRONINGEN_METADATA_DIRECTORY="dataverse_nl/groningen"
HANZE_METADATA_DIRECTORY="dataverse_nl/hanze"
HR_METADATA_DIRECTORY="dataverse_nl/hr"
LEIDEN_METADATA_DIRECTORY="dataverse_nl/leiden"
MAASTRICHT_METADATA_DIRECTORY="dataverse_nl/maastricht"
TILBURG_METADATA_DIRECTORY="dataverse_nl/tilburg"
TRIMBOS_METADATA_DIRECTORY="dataverse_nl/trimbos"
UMCU_METADATA_DIRECTORY="dataverse_nl/umc"
UTRECHT_METADATA_DIRECTORY="dataverse_nl/utrecht"
VU_METADATA_DIRECTORY="dataverse_nl/vu"

CBS_METADATA_DIRECTORY="cbs-metadata"
CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_METADATA_DIRECTORY="easy-metadata"
EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_METADATA_DIRECTORY="liss-metadata"
LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

[production]
ODISSEI_URL="https://portal.staging.odissei.nl"

DATAVERSE_NL_METADATA_DIRECTORY="dataverse_nl-metadata"
RESEARCH_DATA_METADATA_DIRECTORY="dataverse_nl/4tu"
AVANS_METADATA_DIRECTORY="dataverse_nl/avans"
FONTYS_METADATA_DIRECTORY="dataverse_nl/fontys"
GRONINGEN_METADATA_DIRECTORY="dataverse_nl/groningen"
HANZE_METADATA_DIRECTORY="dataverse_nl/hanze"
HR_METADATA_DIRECTORY="dataverse_nl/hr"
LEIDEN_METADATA_DIRECTORY="dataverse_nl/leiden"
MAASTRICHT_METADATA_DIRECTORY="dataverse_nl/maastricht"
TILBURG_METADATA_DIRECTORY="dataverse_nl/tilburg"
TRIMBOS_METADATA_DIRECTORY="dataverse_nl/trimbos"
UMCU_METADATA_DIRECTORY="dataverse_nl/umc"
UTRECHT_METADATA_DIRECTORY="dataverse_nl/utrecht"
VU_METADATA_DIRECTORY="dataverse_nl/vu"

CBS_METADATA_DIRECTORY="cbs-metadata"
CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_METADATA_DIRECTORY="easy-metadata"
EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_METADATA_DIRECTORY="liss-metadata"
LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"