[default]
DATAVERSE_NL_URL="https://dataverse.nl"
SSH_DATASTATION_URL="https://ssh.datastations.nl"
DATAVERSE_NL_REFINER_ENDPOINT = "/metadata-refinement/dataverse-nl"
CBS_REFINER_ENDPOINT = "/metadata-refinement/cbs"
DATASTATION_REFINER_ENDPOINT= "/metadata-refinement/dataverse-nl"

RESEARCH_DATA={"ALIAS"="4tu", "METADATA_DIRECTORY"="@format {this.RESEARCH_DATA_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
AVANS={"ALIAS"="AvansHogeschool", "METADATA_DIRECTORY"="@format {this.AVANS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
FONTYS={"ALIAS"="fontys", "METADATA_DIRECTORY"="@format {this.FONTYS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
GRONINGEN={"ALIAS"="groningen", "METADATA_DIRECTORY"="@format {this.GRONINGEN_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HANZE={"ALIAS"="hanze", "METADATA_DIRECTORY"="@format {this.HANZE_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
HR={"ALIAS"="hr", "METADATA_DIRECTORY"="@format {this.HR_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
LEIDEN={"ALIAS"="leidenuniversity", "METADATA_DIRECTORY"="@format {this.LEIDEN_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
MAASTRICHT={"ALIAS"="maastricht", "METADATA_DIRECTORY"="@format {this.MAASTRICHT_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TILBURG={"ALIAS"="tiu", "METADATA_DIRECTORY"="@format {this.TILBURG_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
TRIMBOS={"ALIAS"="trimbos", "METADATA_DIRECTORY"="@format {this.TRIMBOS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UMCU={"ALIAS"="UMCU", "METADATA_DIRECTORY"="@format {this.UMCU_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
UTRECHT={"ALIAS"="UU", "METADATA_DIRECTORY"="@format {this.UTRECHT_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
VU={"ALIAS"="vuamsterdam", "METADATA_DIRECTORY"="@format {this.VU_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DATAVERSE_NL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATAVERSE_NL_REFINER_ENDPOINT}"}
DANS={"ALIAS"="dans", "METADATA_DIRECTORY"="@format {this.DANS_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.SSH_DATASTATION_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.DATASTATION_REFINER_ENDPOINT}"}
CBS={"ALIAS"="cbs", "METADATA_DIRECTORY"="@format {this.CBS_METADATA_DIRECTORY}", "TEMPLATE_FILE_PATH"="@format {this.CBS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.CBS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}", "REFINER_ENDPOINT"="@format {this.CBS_REFINER_ENDPOINT}"}
LISS={"ALIAS"="liss", "METADATA_DIRECTORY"="@format {this.LISS_METADATA_DIRECTORY}", "TEMPLATE_FILE_PATH"="@format {this.LISS_TEMPLATE_FILE_PATH}", "MAPPING_FILE_PATH"="@format {this.LISS_MAPPING_FILE_PATH}", "DESTINATION_DATAVERSE_URL"="@format {this.ODISSEI_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.ODISSEI_API_KEY}"}

DATAVERSE_NL_METADATA_DIRECTORY="dataverse.nl-metadata"
RESEARCH_DATA_METADATA_DIRECTORY="dataverse.nl-4tu"
AVANS_METADATA_DIRECTORY="dataverse.nl-avans"
FONTYS_METADATA_DIRECTORY="dataverse.nl-fontys"
GRONINGEN_METADATA_DIRECTORY="dataverse.nl-groningen"
HANZE_METADATA_DIRECTORY="dataverse.nl-hanze"
HR_METADATA_DIRECTORY="dataverse.nl-hr"
LEIDEN_METADATA_DIRECTORY="dataverse.nl-leiden"
MAASTRICHT_METADATA_DIRECTORY="dataverse.nl-maastricht"
TILBURG_METADATA_DIRECTORY="dataverse.nl-tilburg"
TRIMBOS_METADATA_DIRECTORY="dataverse.nl-trimbos"
UMCU_METADATA_DIRECTORY="dataverse.nl-umc"
UTRECHT_METADATA_DIRECTORY="dataverse.nl-utrecht"
VU_METADATA_DIRECTORY="dataverse.nl-vu"
CBS_METADATA_DIRECTORY="cbs-metadata"
DANS_METADATA_DIRECTORY="ssh-social-metadata"
LISS_METADATA_DIRECTORY="liss-metadata"

[development]
ODISSEI_URL="http://dataverse:8080"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

[staging]
ODISSEI_URL="https://portal.staging.odissei.nl"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

EASY_TEMPLATE_FILE_PATH="/resources/templates/easy_dataverse_template.json"
EASY_MAPPING_FILE_PATH="/resources/mappings/easy-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"

[production]
ODISSEI_URL="https://portal.dev.odissei.nl"

CBS_TEMPLATE_FILE_PATH="/resources/templates/cbs_dataverse_template.json"
CBS_MAPPING_FILE_PATH="/resources/mappings/cbs-mapping.json"

LISS_TEMPLATE_FILE_PATH="/resources/templates/liss_dataverse_template.json"
LISS_MAPPING_FILE_PATH="/resources/mappings/liss-mapping.json"
