[development]
DESTINATION_DATAVERSE_API_KEY="secret" # Assumes you are using a single dataverse during development
ODISSEI_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"
SICADA_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"

DATAVERSE_NL_API_KEY="secret"
XML2JSON_API_TOKEN="secret"

[production]
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

DATAVERSE_NL_API_KEY="secret"
XML2JSON_API_TOKEN="secret"
