[development]
# Destination Dataverse
DESTINATION_DATAVERSE_API_KEY="secret" # Assumes you are using a single dataverse during development
ODISSEI_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"
SICADA_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"

# Services
XML2JSON_API_TOKEN="secret"

MINIO_SERVER_URL="secret"
AWS_ACCESS_KEY_ID="secret"  # TODO rename to MINOO_KEY
AWS_SECRET_ACCESS_KEY="secret"  # TODO rename to MINOO_SECRECT

[production]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"

MINIO_SERVER_URL="secret"
AWS_ACCESS_KEY_ID="secret"  # TODO rename to MINOO_KEY
AWS_SECRET_ACCESS_KEY="secret"  # TODO rename to MINOO_SECRECT
