[default]
ELSST_SKOSMOS_URL="https://thesauri.cessda.eu"
METADATA_PREFIX="oai_dc"

[development]
debug = true
DOI_MINTER_URL = "http://datacite-minter:9999"
DATAVERSE_IMPORTER_URL="http://dataverse-importer:8091"
PUBLICATION_DATA_UPDATER_URL="http://publication-date-updater:8093"
METADATA_FETCHER_URL="http://metadata-fetcher:8092"
DATAVERSE_MAPPER_URL="http://dataverse-mapper-v2:8094"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dans.knaw.nl"
EMAIL_SANITATION_SERVICE="https://emailsanitizer.labs.dans.knaw.nl/sanitize"
METADATA_REFINER_URL="http://metadata-refiner:7878"
METADATA_ENHANCER_URL="http://metadata-enhancer:7070"
SEMANTIC_API_URL= "http://semanticapi:80/importdoi"
HARVESTER_URL="http://oai-harvester:7890"

[staging]
debug = false
DOI_MINTER_URL = "https://dataciteminter.labs.dans.knaw.nl/submit-to-datacite/draft"
DATAVERSE_IMPORTER_URL="https://dataverse-importer.labs.dans.knaw.nl"
PUBLICATION_DATA_UPDATER_URL="https://dataverse-date-updater.labs.dans.knaw.nl"
METADATA_FETCHER_URL="https://dataverse-fetcher.labs.dans.knaw.nl"
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dans.knaw.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dans.knaw.nl"
EMAIL_SANITIZER_URL="https://emailsanitizer.labs.dans.knaw.nl/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dans.knaw.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dans.knaw.nl"
SEMANTIC_API_URL="http://semanticapi:80/importdoi"
HARVESTER_URL="https://oai-harvester.labs.dans.knaw.nl"

[production]
debug = false
DOI_MINTER_URL = "https://dataciteminter.labs.dans.knaw.nl/submit-to-datacite/register"
DATAVERSE_IMPORTER_URL="https://dataverse-importer.labs.dans.knaw.nl"
PUBLICATION_DATA_UPDATER_URL="https://dataverse-date-updater.labs.dans.knaw.nl"
METADATA_FETCHER_URL="https://dataverse-fetcher.labs.dans.knaw.nl"
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dans.knaw.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dans.knaw.nl"
EMAIL_SANITIZER_URL="https://emailsanitizer.labs.dans.knaw.nl/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dans.knaw.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dans.knaw.nl"
SEMANTIC_API_URL="http://semanticapi:80/importdoi"
HARVESTER_URL="https://oai-harvester.labs.dans.knaw.nl"
