[default]
IISG_URL="https://datasets.iisg.amsterdam"
IISG={"ALIAS"="iisg", "METADATA_DIRECTORY"="@format {this.IISG_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.IISG_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.SICADA_REFINER_ENDPOINT}"}


[development]
SICADA_URL="http://dataverse:8080"
IISG_METADATA_DIRECTORY="iisg-metadata"
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

[production]
SICADA_URL="https://portal.staging.odissei.nl"
IISG_METADATA_DIRECTORY="iisg-metadata"
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"
