[default]
IISG={"ALIAS"="iisg", "BUCKET_NAME"="@format {this.IISG_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.IISG_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.IISG_REFINER_ENDPOINT}"}
SSH={"ALIAS"="ssh", "BUCKET_NAME"="@format {this.SSH_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.SSH_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.SSH_REFINER_ENDPOINT}"}
DVNL={"ALIAS"="dvnl", "BUCKET_NAME"="@format {this.DVNL_BUCKET_NAME}", "SOURCE_DATAVERSE_URL"="@format {this.DVNL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.DVNL_REFINER_ENDPOINT}"}

IISG_BUCKET_NAME="iisg-metadata"
SSH_BUCKET_NAME="ssh-metadata"
DVNL_BUCKET_NAME="dvnl-metadata"

[development]
SICADA_URL="https://dataverse.sicada.charminghat.nl" # sicada test bak
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

IISG_URL="https://datasets.iisg.amsterdam"
IISG_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

SSH_URL="https://test.ssh.datastations.nl"
SSH_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

DVNL_URL="https://dataverse.nl/"
DVNL_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

[staging]
SICADA_URL="https://google.nl"  # TODO set production value
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

IISG_URL="https://datasets.iisg.amsterdam"
IISG_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

SSH_URL="google.nl" # TODO set production value
SSH_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

DVNL_URL="https://dataverse.nl/"
DVNL_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

[production]
SICADA_URL="https://google.nl"  # TODO set production value
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

IISG_URL="https://datasets.iisg.amsterdam"
IISG_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

SSH_URL="google.nl" # TODO set production value
SSH_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

DVNL_URL="https://dataverse.nl/"
DVNL_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"
