[default]
IISG={"ALIAS"="iisg", "METADATA_DIRECTORY"="@format {this.IISG_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.IISG_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.IISG_REFINER_ENDPOINT}"}
SSH={"ALIAS"="ssh", "METADATA_DIRECTORY"="@format {this.SSH_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.SSH_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.SSH_REFINER_ENDPOINT}"}
DVNL={"ALIAS"="dvnl", "METADATA_DIRECTORY"="@format {this.DVNL_METADATA_DIRECTORY}", "SOURCE_DATAVERSE_URL"="@format {this.DVNL_URL}", "DESTINATION_DATAVERSE_URL"="@format {this.SICADA_URL}", "DESTINATION_DATAVERSE_API_KEY"="@format {this.SICADA_API_KEY}", "REFINER_ENDPOINT"="@format {this.DVNL_REFINER_ENDPOINT}"}

[development]
SICADA_URL="http://dataverse:8080"
#SICADA_URL="https://dataverse.sicada.charminghat.nl" # sicada test bak
IISG_METADATA_DIRECTORY="iisg-metadata"
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

IISG_URL="https://datasets.iisg.amsterdam"
IISG_METADATA_DIRECTORY="iisg-metadata"
IISG_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

SSH_URL="https://test.ssh.datastations.nl"
SSH_METADATA_DIRECTORY="ssh-metadata"
SSH_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

DVNL_URL="https://dataverse.nl/"
DVNL_METADATA_DIRECTORY="dvnl-metadata"
DVNL_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

[production]
SICADA_URL="https://google.nl"  # TODO set production value
SICADA_REFINER_ENDPOINT="/metadata-refinement/sicada"

IISG_URL="https://datasets.iisg.amsterdam"
IISG_METADATA_DIRECTORY="iisg-metadata"
IISG_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

SSH_URL="google.nl" # TODO set production value
SSH_METADATA_DIRECTORY="ssh-metadata"
SSH_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"

DVNL_URL="https://dataverse.nl/"
DVNL_METADATA_DIRECTORY="dvnl-metadata"
DVNL_REFINER_ENDPOINT="@format {this.SICADA_REFINER_ENDPOINT}"
